# Replace dependency version in Cargo.toml

[[pre-release-replacements]]
file = "Cargo.toml"
search = 'udf-macros = \{ path = "../udf-macros", version = .* \}'
replace = 'udf-macros = { path = "../udf-macros", version = "{{version}}" }'

[[pre-release-replacements]]
file = "Cargo.toml"
search = 'udf-sys = \{ path = "../udf-sys", version = .* \}'
replace = 'udf-sys = { path = "../udf-sys", version = "{{version}}" }'
