[package]
name = "udf-examples"
version = "0.3.9"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
udf = { path = "../udf" }
lipsum = "0.8.2"
uuid = { version = "1.1.2", features = ["v1", "v3", "v4", "v5", "fast-rng"] }

[dev-dependencies]
testcontainers = "0.14.0"
diesel = { version = "2.0.2", features = ["mysql"] }

[features]
# Used to optionally enable integration tests
backend = []
